### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by DelphiClubItalia** [lminuti/Delphi-WkHtmlToX#1]
https://github.com/lminuti/Delphi-WkHtmlToX/blob/69d3425fe8affd8dde4a838cf382fe8b47da7a86/Samples/01.ApiDemo/MainForm.pas#L110

	wkhtmltopdf_set_global_setting(gs, 'out', PAnsiChar(AnsiString(OutputPath)));

**Comment by lminuti** [comment]
Thank you!

**Comment by lminuti** [comment]
Fixed with the commit 822573d2fb4e923cdf0c3c675534f5b8c824dd6b
